"""Migration for applicant-flagging

Revision ID: 0a57afd03df5
Revises: a9f09b49d862
Create Date: 2025-11-24 16:09:49.309576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a57afd03df5'
down_revision = 'a9f09b49d862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academics__hiring__assignment', sa.Column('flagged', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academics__hiring__assignment', 'flagged')
    # ### end Alembic commands ###
