"""Migration for recurring office hour events. 

Revision ID: 41c5d192f495
Revises: 684f2df8b00e
Create Date: 2024-12-31 01:19:05.259773
Author: Kris Jordan <kris@cs.unc.edu>
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41c5d192f495"
down_revision = "684f2df8b00e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "office_hours_recurrence_pattern",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("recur_monday", sa.Boolean(), nullable=False),
        sa.Column("recur_tuesday", sa.Boolean(), nullable=False),
        sa.Column("recur_wednesday", sa.Boolean(), nullable=False),
        sa.Column("recur_thursday", sa.Boolean(), nullable=False),
        sa.Column("recur_friday", sa.Boolean(), nullable=False),
        sa.Column("recur_saturday", sa.Boolean(), nullable=False),
        sa.Column("recur_sunday", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "office_hours", sa.Column("recurrence_pattern_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "office_hours__recurrence_pattern_id_fkey",
        "office_hours",
        "office_hours_recurrence_pattern",
        ["recurrence_pattern_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "office_hours__recurrence_pattern_id_fkey",
        "office_hours",
        type_="foreignkey",
    )
    op.drop_column("office_hours", "recurrence_pattern_id")
    op.drop_table("office_hours_recurrence_pattern")
    # ### end Alembic commands ###
