"""Migration for 524-hiring-admin

Revision ID: 8fff82538f2e
Revises: bc68e4844a24
Create Date: 2024-08-02 09:20:14.617600

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8fff82538f2e"
down_revision = "bc68e4844a24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academics__hiring__level",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("salary", sa.Float(), nullable=False),
        sa.Column("load", sa.Float(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum("IOR", "PHD", "MS", "UG", name="hiringlevelclassification"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "academics__hiring__assignment",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("term_id", sa.String(length=6), nullable=False),
        sa.Column("course_site_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("application_review_id", sa.Integer(), nullable=True),
        sa.Column("hiring_level_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "COMMIT", "FINAL", name="hiringassignmentstatus"),
            nullable=False,
        ),
        sa.Column("position_number", sa.String(), nullable=True),
        sa.Column("epar", sa.String(), nullable=True),
        sa.Column("i9", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("modified", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_review_id"],
            ["academics__hiring__application_review.id"],
        ),
        sa.ForeignKeyConstraint(
            ["course_site_id"],
            ["course_site.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hiring_level_id"],
            ["academics__hiring__level.id"],
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["academics__term.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "academics__hiring_application_review_idx",
        "academics__hiring__assignment",
        ["application_review_id"],
        unique=False,
    )
    op.create_index(
        "academics__hiring_course_site_idx",
        "academics__hiring__assignment",
        ["course_site_id"],
        unique=False,
    )
    op.create_index(
        "academics__hiring_term_idx",
        "academics__hiring__assignment",
        ["term_id", "hiring_level_id"],
        unique=False,
    )
    op.create_index(
        "academics__hiring_user_idx",
        "academics__hiring__assignment",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "academics__hiring_user_idx", table_name="academics__hiring__assignment"
    )
    op.drop_index(
        "academics__hiring_term_idx", table_name="academics__hiring__assignment"
    )
    op.drop_index(
        "academics__hiring_course_site_idx", table_name="academics__hiring__assignment"
    )
    op.drop_index(
        "academics__hiring_application_review_idx",
        table_name="academics__hiring__assignment",
    )
    op.drop_table("academics__hiring__assignment")
    op.drop_table("academics__hiring__level")
    op.execute("DROP TYPE hiringassignmentstatus")
    op.execute("DROP TYPE hiringlevelclassification")
    # ### end Alembic commands ###
