"""Migration for community-agreement

Revision ID: 90c56e5464ff
Revises: 17162b9faf79
Create Date: 2024-02-10 13:27:20.995130

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90c56e5464ff"
down_revision = "17162b9faf79"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "accepted_community_agreement",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "accepted_community_agreement")
    # ### end Alembic commands ###
