"""Migration for ta-application

Revision ID: 92214831537d
Revises: 90c56e5464ff
Create Date: 2024-04-22 20:13:12.264532

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92214831537d"
down_revision = "90c56e5464ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.Column("academic_hours", sa.Integer(), nullable=False),
        sa.Column("extracurriculars", sa.String(), nullable=True),
        sa.Column("expected_graduation", sa.String(), nullable=False),
        sa.Column("program_pursued", sa.String(), nullable=False),
        sa.Column("other_programs", sa.String(), nullable=True),
        sa.Column("gpa", sa.Float(), nullable=False),
        sa.Column("comp_gpa", sa.Float(), nullable=True),
        sa.Column(
            "comp_227",
            sa.Enum("COMPENSATION", "CREDIT", "EITHER", name="comp227"),
            nullable=True,
        ),
        sa.Column("intro_video_url", sa.String(), nullable=False),
        sa.Column("prior_experience", sa.String(), nullable=True),
        sa.Column("service_experience", sa.String(), nullable=True),
        sa.Column("additional_experience", sa.String(), nullable=True),
        sa.Column("ta_experience", sa.String(), nullable=True),
        sa.Column("best_moment", sa.String(), nullable=True),
        sa.Column("desired_improvement", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "section_application",
        sa.Column("preference", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["academics__section.id"],
        ),
        sa.PrimaryKeyConstraint("section_id", "application_id"),
    )
    op.add_column(
        "academics__user_section",
        sa.Column("application_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        "academics__user_section_application",
        "academics__user_section",
        "application",
        ["application_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "academics__user_section_application",
        "academics__user_section",
        type_="foreignkey",
    )
    op.drop_column("academics__user_section", "application_id")
    op.drop_table("section_application")
    op.drop_table("application")
    op.execute("""DROP TYPE comp227""")
    # ### end Alembic commands ###
