"""Migration for office hours ticket cooldowns

Revision ID: a9f09b49d862
Revises: 41c5d192f495
Create Date: 2025-05-01 15:11:11.356292
Author: Jade Keegan <jade@cs.unc.edu>
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f09b49d862'
down_revision = '41c5d192f495'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'course_site', 
        sa.Column(
            'minimum_ticket_cooldown', 
            sa.Integer(), 
            nullable=False, 
            default=0, 
            server_default=sa.text('0'),
        ),
    )
    op.add_column(
        'course_site', 
        sa.Column(
            'max_tickets_per_day', 
            sa.Integer(), 
            nullable=False,
            default=100,
            server_default=sa.text('100'),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_site', 'max_tickets_per_day')
    op.drop_column('course_site', 'minimum_ticket_cooldown')
    # ### end Alembic commands ###
