"""Migration for 396-room-capacity

Revision ID: eeed6d309629
Revises: 90c56e5464ff
Create Date: 2024-04-22 17:14:54.507381

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eeed6d309629"
down_revision = "90c56e5464ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "room", sa.Column("description", sa.String(), nullable=False, server_default="")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("room", "description")
    # ### end Alembic commands ###
